### ISSUE TITLE
Blockchain export broken

### ISSUE THREAD

**Issue by punkrock** [LiskHQ/lisk-core#902] opened 2023-12-25 22:40 UTC
Exporting the blockchain is not working on 4.0.1 - it produces broken blockchain db that show this error if imported (block height varies based on when you export):

```
0|lisk-core-v4  |     Error: Invalid engine state. Conflict at engine height 23557281 and 
0|lisk-core-v4  |     application state 23557280.
```

**Comment by nagdahimanshu** [comment] 2023-12-27 11:51
@punkrock I am not able to reproduce this issue. Can you please provide more details on it?

**Comment by przemerr** [comment] 2023-12-27 12:06
@nagdahimanshu 
`lisk-core blockchain:export -o ./snapshot`
and importing that snapshot on a clean installation gives that error, it was tested on
it's was tested on `mainnet` so it maybe specific to that network

also sometimes the blockchain:export command gives:
```
Exporting blockchain:
   /home/lisk/.lisk/lisk-core/data
    Error: did not encounter expected EOF
    Code: EOF
```
it's not consistent

**Comment by sameersubudhi** [comment] 2024-02-19 10:51
Unable to reproduce. Closing the issue.

This could be due to the inconsistent node state caused due to crashing of the node when running older versions (0.7.3 or older) of Lisk Service.

**Closed by sameersubudhi** 2024-02-19 10:51 UTC
Labels: type: bug
