### ISSUE TITLE
lisk-core start error - after npm clean install

### ISSUE THREAD

**Issue by JesusTheHun** [LiskHQ/lisk-core#536] opened 2021-09-05 11:12 UTC
The script still runs but I get this error :

```bash
% lisk-core start --network mainnet --enable-http-api-plugin --api-ws --enable-forger-plugin
Starting Lisk Core at /Users/jonathan/.lisk/lisk-core.
Genesis block from "mainnet" does not exists.
Downloading genesis block from https://downloads.lisk.io/lisk/mainnet/genesis_block.json.tar.gz
Downloaded to path: /Users/jonathan/.lisk/lisk-core/config/mainnet/genesis_block.json.tar.gz.
Verified checksum: a69fe85969ce8727b6490a07ced612bbc36a5c377a54f2b6fab58c058d1663b5.
Extracting genesis block file.
Removing downloaded genesis block
Download completed.
   /Users/jonathan/.lisk/lisk-core/config/mainnet/genesis_block.json
(node:74174) UnhandledPromiseRejectionWarning: Error: Specified key blocks:height:00f843d4 does not exist
    at parseError (/Users/jonathan/.nvm/versions/node/v12.20.1/lib/node_modules/lisk-core/node_modules/lisk-framework/dist-node/controller/bus.js:21:12)
    at Bus.invoke (/Users/jonathan/.nvm/versions/node/v12.20.1/lib/node_modules/lisk-core/node_modules/lisk-framework/dist-node/controller/bus.js:131:23)
(node:74174) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:74174) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ManuGowda** [comment] 2021-09-05 19:27
@JesusTheHun can you confirm which version of `lisk-core` you are using? I tested with `lisk-core -v
lisk-core/3.0.0 darwin-x64 node-v12.22.1` and it seem to work fine. 

Maybe you are querying something in cli? `lisk-core block:get height`? and the block doesn't exists?

**Comment by JesusTheHun** [comment] 2021-09-06 06:27
```bash
lisk-core -v
lisk-core/3.0.0 darwin-x64 node-v12.20.1
```

This is during the start, when it's importing the genesis block I believe, not when I perform a request

**Comment by JesusTheHun** [comment] 2021-09-06 06:29
Ok I just tried without the forger plugin and there is no error. So I think it's the sync process of the forger plugin

**Comment by ManuGowda** [comment] 2021-09-06 08:54
> Ok I just tried without the forger plugin and there is no error. So I think it's the sync process of the forger plugin

I tried to run with the exact command you shared `lisk-core start --network mainnet --enable-http-api-plugin --api-ws --enable-forger-plugin` I dint face any issues, try to clean up the data under `~/.lisk/lisk-core` and try once more?

**Comment by ManuGowda** [comment] 2021-09-06 10:08
Confirmed the issue with @JesusTheHun, the issue is no longer reproducible, so closing the issue.

Logs from testing.
```
Starting Lisk Core at /Users/manu/.lisk/lisk-core.
Genesis block from "mainnet" does not exists.
Downloading genesis block from https://downloads.lisk.io/lisk/mainnet/genesis_block.json.tar.gz
Downloaded to path: /Users/manu/.lisk/lisk-core/config/mainnet/genesis_block.json.tar.gz.
Verified checksum: a69fe85969ce8727b6490a07ced612bbc36a5c377a54f2b6fab58c058d1663b5.
Extracting genesis block file.
Removing downloaded genesis block
Download completed.
   /Users/manu/.lisk/lisk-core/config/mainnet/genesis_block.json
```

**Closed by ManuGowda** 2021-09-06 10:08 UTC
Labels: type: bug, status: discussion
